import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TanstackProvider from "@/components/providers/TanstackProvider";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/components/providers/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Alessence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className="min-h-screen w-full bg-white relative">
          <ReduxProvider>
            <TanstackProvider>
              {children}
              <Toaster />
            </TanstackProvider>
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
